---
- name: Reset User Password
  vars_prompt:
    - name: target_host
      prompt: "Set target host"
      private: no
    - name: target_user
      prompt: "Set Username"
      private: no
    - name: target_password
      prompt: "Set user password"
      private: no
  hosts:  "{{ target_host }}"
  become: yes
  tasks:
    - name: Reset User Password
      ansible.builtin.user:
        name: "{{ target_user }}"
        state: present
        password: "{{ target_password| password_hash('sha512') }}"