---
- name: Reset User Password
  vars_prompt:
    - name: target_user
      prompt: "Set Username"
      private: no
  vars:
    email_sender: "administrator@nota.ai"
    target_password: "{{ lookup('community.general.random_string', upper=false, lower=false, special=false, numbers=true) }}"
    #target_password: "{{ lookup('ansible.builtin.password', '/dev/null', length=10 ) }}".
  hosts: localhost
  tasks:
    - name: Get User email from LDAP Server with   community.general.ldap_search
      community.general.ldap_search:
         server_uri: "ldap://nas-admin.nota.ai"
         bind_dn: "{{ lookup('ansible.builtin.env', 'BIND_DN') }}"
         bind_pw: "{{ lookup('ansible.builtin.env', 'BIND_PW') }}"
         dn: "{{ lookup('ansible.builtin.env', 'BASE_DN')|default('cn=users,dc=nas-admin,dc=nota,dc=ai') }}"
         scope: onelevel
         filter: "(uid={{ target_user }})"
         attrs:
           - mail
      register: user_email
    - name: Create New Password
      run_once: true
      local_action:
        module: ansible.builtin.set_fact
        target_password: "{{ lookup('community.general.random_string', upper=true, lower=true, special=false, numbers=true) }}"
    - name: Reset User Password
      run_once: true
      local_action:
        module: community.general.ldap_passwd
        server_uri: "ldap://nas-admin.nota.ai"
        dn: "uid={{ target_user }},{{ lookup('ansible.builtin.env', 'BASE_DN')|default('cn=users,dc=nas-admin,dc=nota,dc=ai') }}"
        passwd: "{{ target_password }}"
        bind_dn: "{{ lookup('ansible.builtin.env', 'BIND_DN') }}"
        bind_pw: "{{ lookup('ansible.builtin.env', 'BIND_PW') }}"
    - name: Send the  password to user {{ target_user }} / {{ user_email.results[0].mail }}
      run_once: true
      local_action:
        module: community.general.mail
        host: "{{ lookup('ansible.builtin.env', 'SMTP_HOST') }}"
        port: "{{ lookup('ansible.builtin.env', 'SMTP_PORT')|default('587')|int }}"
        username: "{{ lookup('ansible.builtin.env', 'SMTP_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'SMTP_PASSWORD') }}"
        to: "{{ user_email.results[0].mail }}"
        sender: "{{ email_sender }}"
        subject: Your account '{{ target_user }}''s password on LDAP has been updated
        body: |
            A password for  account  '"{{ target_user }}"' has been changed.

            Password:
              * {{ target_password }}
          
            You can use it to login to Nota Internal System ( the monitoring dashboard, the repository manager, Docker private registry, etc. )