---
- name: Update User Information
  vars_prompt:
    - name: target_host
      prompt: "Set target host"
      private: no
      default: "all"
    - name: username
      prompt: "Set username"
      private: no
    - name: newpassword
      prompt: "Set user's newpassword"
      private: no
      default: "ChangeYourPassword1@"
    - name: user_groups
      prompt: "Set group names for user"
      private: no
      default: "users,docker"
  hosts: "{{ target_host }}"
  become: yes
  tasks:
    - name: Update User Password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ newpassword | password_hash('sha512') }}"
        groups: "{{ user_groups }}"
        append: yes