all:
  children:
    4th:
      hosts:
        argus:
          ansible_host: 192.168.1.166
          ansible_port: 2222
      vars:
        ansible_user: '{{ lookup("env", "ANSIBLE_USERNAME") }}'
        ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
        ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
        ansible_python_interpreter: python3
