all:
  children:
    mybox:
      hosts:
        tahoe:
          ansible_host: "{{ lookup('env', 'TARGET_IP', default='tahoe') }}"
      vars:
        ansible_user: "{{ lookup('env', 'ANSIBLE_USERNAME', default='ubuntu') }}"
        ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD', default='ubuntu') }}"
        ansible_become_password: "{{ lookup('env', 'ANSIBLE_BECOME_PASSWORD', default='ubuntu')}}"
        ansible_python_interpreter: python3
