version: "3"

services:
  jenkins_web:
    image: notadockerhub/jenkins:latest
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile
#    environment:
#      - JENKINS_OPTS="--httpPort=8080"
    ports:
      - "50001:8080"
#      - "50000:50000"
    volumes:
       - ${JENKINS_HOME:-/raid1/jenkins_home}:/var/jenkins_home
