rbp:
  hosts:
    rbp5:
      ansible_host: 192.168.50.59
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('', true) }}"
    ansible_become_password: "{{ lookup('env', 'ANSIBLE_BECOME_PASSWORD') | default('', true) }}"
