all:
  children:
    daejeon:
      hosts:
        3090a:
          ansible_host: 10.169.20.110
        3090b:
          ansible_host: 10.169.20.111
        3090c:
          ansible_host: 10.169.20.112
        3090d:
          ansible_host: 10.169.20.113
        3090e:
          ansible_host: 10.169.20.115
        3090f:
          ansible_host: 10.169.20.116
        3090g:
          ansible_host: 10.169.20.117
        3090h:
          ansible_host: 10.169.20.118
        3090i:
          ansible_host: 10.169.20.121
        3090j:
          ansible_host: 10.169.20.122
        3090k:
          ansible_host: 10.169.20.123
        3090l:
          ansible_host: 10.169.20.124
        3090m:
          ansible_host: 10.169.20.120
        beauty:
          ansible_host: 10.169.20.103
        dasom:
          ansible_host: 10.169.20.109
        dgx-a100:
          ansible_host: 10.169.20.130
        galilei:
          ansible_host: 10.169.20.107
        honest: # A100
          ansible_host: 10.169.20.100
        hope:
          ansible_host: 10.169.20.108
        love:
          ansible_host: 10.169.20.101
        nota-server-01:
          ansible_host: 10.169.20.125
        nota-server-02:
          ansible_host: 10.169.20.126
        nota-server-03:
          ansible_host: 10.169.20.127
        nota-server-04:
          ansible_host: 10.169.20.128
        nota-server-05:
          ansible_host: 10.169.20.129
        sejong:
          ansible_host: 10.169.20.106
        truth:
          ansible_host: 10.169.20.102
        wisdom:
          ansible_host: 10.169.20.104
        wish:
          ansible_host: 10.169.20.105
    seoul:
      children:
        seoul_gpu:
          hosts:
            a30a:
              ansible_host: 10.169.10.28
            gpu307090:
              ansible_host: 10.169.10.29
            nota-its:
              ansible_host: 10.169.10.34
          vars:
            ansible_port: 2222
            ansible_user: '{{ lookup("env", "ANSIBLE_USERNAME") }}'
            ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
            ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
            ansible_python_interpreter: python3
        seoul_workstation:
          hosts:
            adam:
              ansible_host: 10.169.10.15
            argus:
              ansible_host: 10.169.10.12
            eve:
              ansible_host: 10.169.10.14
  vars:
    ansible_port: 2222
    ansible_user: '{{ lookup("env", "ANSIBLE_USERNAME") }}'
    ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
    ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
    ansible_python_interpreter: python3
