all:
  children:
    kaist_servers:
      hosts:
        3090a:
          ansible_host: 143.248.251.90
        3090b:
          ansible_host: 143.248.251.91
        3090c:
          ansible_host: 143.248.251.98
        3090d:
          ansible_host: 143.248.251.99
      vars:
        ansible_port: 2222
        ansible_user: '{{ lookup("env", "ANSIBLE_USER_kaist") }}'
        ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD_kaist") }}'
        ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD_kaist") }}'
        ansible_python_interpreter: python3
    seocho_idc_public:
      hosts:
        3090e:
          ansible_host: 221.139.0.143
        3090f:
          ansible_host: 221.139.0.144
        3090g:
          ansible_host: 221.139.0.145
        3090h:
          ansible_host: 221.139.0.146
      vars:
        ansible_port: 2222
        ansible_user: '{{ lookup("env", "ANSIBLE_USER_seocho") }}'
        ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD_seocho") }}'
        ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD_seocho") }}'
        ansible_python_interpreter: python3