all:
  children:
    aws:
      hosts:
        th:
          ansible_host: netspresso-searcher-th
        core:
          ansible_host: netspresso-searcher-core
      vars:
        ansible_port: 22
        ansible_user: ubuntu
        ansible_python_interpreter: python3