version: "3"

services:
  dcgm-exporter:
    cap_add:
    - SYS_ADMIN
    - DAC_READ_SEARCH
    environment:
      - DCGM_EXPORTER_LISTEN=":30001"
      - DCGM_EXPORTER_INTERVAL="5000"
      - DCGM_EXPORTER_COLLECTORS="/etc/dcgm-exporter/default-counters.csv"
    image: nvcr.io/nvidia/k8s/dcgm-exporter:2.2.9-2.5.0-ubi8
    network_mode: "host"
    ipc: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
       - ./exporters:/etc/dcgm-exporter

