---
- name: Change all user passwor valid date
  hosts: all
  become: yes
  vars:
    script_file: change-passwd-valid.sh
  tasks:
    - name: Copy script to remote 
      ansible.builtin.copy:
        src: change-passwd-valid.sh
        dest: /tmp/change-passwd-valid.sh
    - name: Set permission
      shell: chmod +x /tmp/change-passwd-valid.sh
    - name: Check a file
      shell: ls -l /tmp
      register: ps
    - name: Run Command
      shell: /tmp/change-passwd-valid.sh
      register: ps22
      ignore_errors: true