---
- name: Create User Account
  vars_prompt:
    - name: target_host
      prompt: "Set target host"
      private: no
    - name: user_name
      prompt: "Set username"
      private: no
    - name: user_email
      prompt: "Set user email address"
      private: no
    - name: user_home
      prompt: "Set user home"
      private: no
  vars:
    user_shell: "/bin/bash"
    target_password: "ChangeYourPassword1@"
  hosts: "{{ target_host }}"
  become: yes
  tasks:
    - name: Create user account
      ansible.builtin.user:
        name: "{{ user_name }}"
        password:  "{{ target_password| password_hash('sha512') }}"
        state: present
        shell: "{{ user_shell }}"
        home: "{{ user_home }}"
        groups: "users,docker"
        append: yes
    - name: Create user .ssh directory 
      ansible.builtin.file:
        path: "{{ user_home }}/.ssh"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: 0700
    - name: Create user key 
      community.crypto.openssh_keypair:
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: 0600
        path: "{{ user_home }}/.ssh/id_rsa"
    - name: Set authorized key
      shell: su - {{ user_name }} bash -c 'cat {{ user_home }}/.ssh/id_rsa.pub > {{ user_home }}/.ssh/authorized_keys'
    - name: Send a key file to a user
      community.general.mail:
        host: 1.235.98.12
        port: 25
        to: "{{ user_email }}" 
        sender: administrator@nota.ai
        subject: Your account '{{ user_name }} on {{ target_host }}' is  created
        body: |
            An account  "{{ user_name }}" on "{{ target_host }}" is created. Its password is

              * {{ target_password }}

            You can log onto {{ target_host }} with an attached private key file.
            Copy a file to $HOME/.ssh and change its permission as 0600

              $> chmod 0600 ~/.ssh/id_rsa
              $> ssh -p 2222 -i ~/.ssh/id_rsa {{ user_name }}@{{ ansible_default_ipv4.address }}
            
        attach:
          - "{{ user_home }}/.ssh/id_rsa"
    - name: Download a key file
      fetch:
        src: "{{ user_home }}/.ssh/id_rsa"
        dest: ./id_rsa_{{ user_name }}
        flat: yes
    - name: Remove a key file on the server
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - ~{{ target_user }}/.ssh/id_rsa
        - ~{{ target_user }}/.ssh/id_rsa.pub
