---
- name: Create User Account
  vars_prompt:
    - name: target_user
      prompt: "Set username"
      private: no
    - name: user_email
      prompt: "Set user email address"
      private: no
    - name: user_home
      prompt: "Set user home"
      private: no
  vars:
    user_shell: "/bin/bash"
    target_password: "Postech2001!@$"
    email_sender: "administrator@nota.ai"
    smtp_host: '{{ lookup("env", "SMTP_HOST") }}'
    smtp_username: '{{ lookup("env", "SMTP_USERNAME") }}'
    smtp_password: '{{ lookup("env", "SMTP_PASSWORD") }}'
  hosts: localhost
  tasks:
    - name: Create one user in LDAP
      run_once: true
      local_action:
        module: community.general.ldap_entry
        server_uri: "ldap://nas-admin.nota.ai"
        dn: "uid={{ target_user }},{{ lookup('ansible.builtin.env', 'BASE_DN')|default('cn=users,dc=nas-admin,dc=nota,dc=ai') }}"
        objectClass:
          - inetOrgPerson
          - apple-user
          - extensibleObject
          - organizationalPerson
          - posixAccount
          - person
          - sambaSamAccount
          - sambaIdmapEntry
          - shadowAccount
          - top
        attributes:
          sn: "{{ target_user }}"
          cn: "{{ target_user }}"
          uid: "{{ target_user }}"
          mail: "{{ user_email }}"
          uidNumber: 2000001
          gidNumber: 2000001
          homeDirectory: "{{ user_home }}"
          #userPassword: "{{ target_password| password_hash('sha512') }}"
          memberOf:
            - "cn=users,cn=groups,dc=nas-admin,dc=nota,dc=ai"
            - "cn=users_local,cn=groups,dc=nas-admin,dc=nota,dc=ai"
            - "cn=docker_local,cn=groups,dc=nas-admin,dc=nota,dc=ai"
            - "cn=rnd,cn=groups,dc=nas-admin,dc=nota,dc=ai"
            - "cn=Directory Consumers,cn=groups,dc=nas-admin,dc=nota,dc=ai"
        bind_dn: "{{ lookup('ansible.builtin.env', 'BIND_DN') }}"
        bind_pw: "{{ lookup('ansible.builtin.env', 'BIND_PW') }}"