---
- name: Create User Account
  vars_prompt:
    - name: target_host
      prompt: "Set target host"
      private: no
    - name: target_user
      prompt: "Set username"
      private: no
    - name: user_email
      prompt: "Set user email address"
      private: no
    - name: user_home
      prompt: "Set user home"
      private: no
  vars:
    user_shell: "/bin/bash"
    target_password: "ChangeYourPassword1@"
    email_sender: "administrator@nota.ai"
    smtp_host: '{{ lookup("env", "SMTP_HOST") }}'
    smtp_username: '{{ lookup("env", "SMTP_USERNAME") }}'
    smtp_password: '{{ lookup("env", "SMTP_PASSWORD") }}'
  hosts: "{{ target_host }}"
  become: yes
  tasks:
    - name: Create user account
      ansible.builtin.user:
        name: "{{ target_user }}"
        password:  "{{ target_password| password_hash('sha512') }}"
        state: present
        shell: "{{ user_shell }}"
        home: "{{ user_home }}"
        groups: "users,docker"
        append: yes
    - name: Create user .ssh directory 
      ansible.builtin.file:
        path: "{{ user_home }}/.ssh"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: 0700
    - name: Create user key 
      community.crypto.openssh_keypair:
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: 0600
        path: "{{ user_home }}/.ssh/id_rsa"
    - name: Set authorized key
      shell: su - {{ target_user }} bash -c 'cat {{ user_home }}/.ssh/id_rsa.pub > {{ user_home }}/.ssh/authorized_keys'
    - name: Send a key file to a user
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ lookup('ansible.builtin.env', 'SMTP_PORT')|default('587')|int }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"        
        to: "{{ user_email }}" 
        sender: "{{ email_sender }}"
        subject: Your account '{{ target_user }} on {{ target_host }}' is  created
        body: |
            An account  "{{ target_user }}" on "{{ target_host }}" is created. Its password is

              * {{ target_password }}

            You can log onto {{ target_host }} with an attached private key file.
            Copy a file to $HOME/.ssh and change its permission as 0600

              $> chmod 0600 ~/.ssh/id_rsa
              $> ssh -p 2222 -i ~/.ssh/id_rsa {{ target_user }}@{{ ansible_default_ipv4.address }}
            
        attach:
          - "{{ user_home }}/.ssh/id_rsa"
    - name: Download a key file
      fetch:
        src: "{{ user_home }}/.ssh/id_rsa"
        dest: ./id_rsa_{{ target_user }}
        flat: yes
    - name: Remove a key file on the server
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - ~{{ target_user }}/.ssh/id_rsa
        - ~{{ target_user }}/.ssh/id_rsa.pub
