---
- name: Register Existing SSH Key
  vars_prompt:
    - name: target_host
      prompt: "Set target host"
      private: no
    - name: target_user
      prompt: "Set Username"
      private: no
    - name: user_email
      prompt: "Set user email"
      private: no
    - name: key_file_path
      prompt: "Private key file path: "
      private: no
  vars:
    email_sender: "administrator@nota.ai"
  hosts: "{{ target_host }}"
  tasks:
    - name: Get Hostname and IP Address
      shell: "echo {{ ansible_hostname }} : {{ ansible_default_ipv4.address }}"
      register: ip_outputs
    - set_fact:
        all_hosts: "{{ ansible_play_hosts | map('extract', hostvars, 'ip_outputs') | map(attribute='stdout') | list }}"
      delegate_to: localhost
      run_once: true
    - name: Create SSH Directory
      become: true
      file:
        path: "~{{ target_user }}/.ssh"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: 0700
    - name: Create a public key from private key file
      delegate_to: localhost
      run_once: true
      shell: ssh-keygen -y -f {{ key_file_path }} > {{ key_file_path }}.pub
    - name: Upload public key
      become: true
      ansible.builtin.copy:
        src: "{{ key_file_path }}.pub"
        dest: "~{{ target_user }}/.ssh/{{ target_user }}.pub"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: 0700
    - name: Set authorized key
      become: true
      shell: su - {{ target_user }} bash -c 'cat ~{{ target_user }}/.ssh/{{ target_user }}.pub >> ~{{ target_user }}/.ssh/authorized_keys'
    - name: Send a key file to a user
      delegate_to: localhost
      run_once: true
      community.general.mail:
        host: "{{ lookup('ansible.builtin.env', 'SMTP_HOST') }}"
        username: "{{ lookup('ansible.builtin.env', 'SMTP_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'SMTP_PASSWORD') }}"
        port: "{{ lookup('ansible.builtin.env', 'SMTP_PORT')|default('587')|int }}"
        to: "{{ user_email }}" 
        sender: "{{ email_sender }}"
        subject: Your account '{{ target_user }} on {{ ansible_play_hosts | join(', ') }}' get a new ssh key
        body: |
            A new ssh public key is appened to ~{{ target_user }}/.ssh/authorized_keys
          
            Hosts:
            {% for item in all_hosts %}
              * {{ item }}
            {% endfor %}

            You can log onto {{ ansible_hostname }} with an attached private key file.
            Copy a file to $HOME/.ssh and change its permission as 0600

              $> chmod 0600 ~/.ssh/{{ key_file_path | basename }}
              $> ssh -p 2222 -i ~/.ssh/{{ key_file_path | basename }} {{ target_user}}@HOST_ADDRESS
        attach:
          - "{{ key_file_path }}"
    - name: Remove a key file
      delegate_to: localhost
      run_once: true
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ key_file_path }}"
        - "{{ key_file_path }}.pub"