---
- name: Reset User Password
  vars:
    target_user: shjeon
    target_password: ChangeYourPassword1@
  hosts: 
    - honest 
    - beauty
    - wisdom
  become: yes
  tasks:
    - name: Reset User Password
      ansible.builtin.user:
        name: "{{ target_user }}"
        state: present
        password: "{{ target_password| password_hash('sha512') }}"