---
- name: Reset User Password
  vars_prompt:
    - name: target_host
      prompt: "Set target host"
      private: no
    - name: target_user
      prompt: "Set Username"
      private: no
    - name: user_email
      prompt: "Set user email"
      private: no
  vars:
    email_sender: "administrator@nota.ai"
    key_file_name: "new_ssh_key_file"
    target_password: "password"
  hosts: "{{ target_host }}"
  tasks:
    - name: Get Hostname and IP Address
      shell: "echo {{ ansible_hostname }} : {{ ansible_default_ipv4.address }}"
      register: ip_outputs
    - set_fact:
        all_hosts: "{{ ansible_play_hosts | map('extract', hostvars, 'ip_outputs') | map(attribute='stdout') | list }}"
      delegate_to: localhost
      run_once: true
    - name: Create New Password
      run_once: true
      local_action:
        module: ansible.builtin.set_fact
        target_password: "{{ lookup('ansible.builtin.password', '/dev/null', length=10 ) }}"
    - name: Create SSH Directory
      become: true
      file:
        path: "~{{ target_user }}/.ssh"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: 0700
    - name: Reset User Password
      become: true
      ansible.builtin.user:
        name: "{{ target_user }}"
        state: present
        password: "{{ target_password| password_hash('sha512') }}"
    - name: Create new ssh key for a user
      run_once: true
      local_action: 
        module: community.crypto.openssh_keypair
        path: "{{ key_file_name }}"        
    - name: Upload public key 
      become: true
      ansible.builtin.copy:
        src: "{{ key_file_name }}.pub"
        dest: "~{{ target_user }}/.ssh/{{ key_file_name }}.pub"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: 0700
    - name: Upload private key 
      become: true
      ansible.builtin.copy:
        src: "{{ key_file_name }}"
        dest: "~{{ target_user }}/.ssh/{{ key_file_name }}"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: 0700        
    - name: Set authorized key
      become: true
      shell: su - {{ target_user }} bash -c 'cat ~{{ target_user }}/.ssh/{{ key_file_name }}.pub >> ~{{ target_user }}/.ssh/authorized_keys'
    - name: Send a key file to a user
      run_once: true
      local_action: 
        module: community.general.mail
        host: "{{ lookup('ansible.builtin.env', 'SMTP_HOST') }}"
        port: "{{ lookup('ansible.builtin.env', 'SMTP_PORT')|default('587')|int }}"
        username: "{{ lookup('ansible.builtin.env', 'SMTP_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'SMTP_PASSWORD') }}"
        to: "{{ user_email }}" 
        sender: "{{ email_sender }}"
        subject: Your account '{{ target_user }} on {{ ansible_play_hosts | join(', ') }}' has been updated
        body: |
            A password for  account  "{{ target_user }}" on "{{ ansible_play_hosts | join(', ') }}" has been changed
            and new ssh key file is registered.

            Password:
              * {{ target_password }}
            Hosts:
            {% for item in all_hosts %}
              * {{ item }}
            {% endfor %}

            You can log onto {{ ansible_hostname }} with an attached private key file.
            Copy a file to $HOME/.ssh and change its permission as 0600

              $> chmod 0600 ~/.ssh/{{ key_file_name }}
              $> ssh -p 2222 -i ~/.ssh/{{ key_file_name }} {{ target_user}}@HOST_ADDRESS
        attach:
          - "{{ key_file_name }}"
    - name: Remove user key file
      run_once: true
      local_action:
        module: ansible.builtin.file
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ key_file_name }}"
        - "{{ key_file_name }}.pub"