---
- name: Reset User Password
  vars_prompt:
    - name: target_user
      prompt: "Set Username"
      private: no
    - name: target_password
      prompt: "Set user password"
      private: no
  hosts: localhost
  tasks:
    - name: Reset User Password
      run_once: true
      local_action:
        module: community.general.ldap_passwd
        server_uri: "ldap://nas-admin.nota.ai"
        dn: "uid={{ target_user }},{{ lookup('ansible.builtin.env', 'BASE_DN')|default('cn=users,dc=nas-admin,dc=nota,dc=ai') }}"
        passwd: "{{ target_password }}"
        bind_dn: "{{ lookup('ansible.builtin.env', 'BIND_DN') }}"
        bind_pw: "{{ lookup('ansible.builtin.env', 'BIND_PW') }}"