#SPDX-License-Identifier: MIT-0
---
- name: Run shell file
  ansible.builtin.script:
    cmd: hello.sh
- name: Copy file
  ansible.builtin.copy:
    src: hello.sh
    dest: /tmp/hello.sh
    mode: '0755'
- name: Print org name
  ansible.builtin.debug:
    msg: "Organization name is: {{ org_name }}"
- name: Create config file from template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /tmp/nginx.conf