---
- name: Check Ansible Functions
  hosts: all
  tasks:
    - name: Print all facts
      debug:
        var: go_target_directory
  vars:
    go_target_directory: >-
      {% if ansible_facts['os_family'] == "Debian" %}{{ (ansible_user_dir + '/.local') }}{% elif ansible_facts['os_family'] == "Darwin" %}{{ (ansible_user_dir + '/Library') }}{% else %}{{ ('~/program') }}{% endif %}
