---
- name: Create User Account
  hosts: 3090d
  become: yes
  vars:
    user_email: "all4dich@naver.com"
  tasks:
    - name: Send a key file to a user
      community.general.mail:
        host: 1.235.98.12
        port: 25
        to: "{{ user_email }}"
        sender: administrator@nota.ai
        subject: test email from sunjoo
        body: |
          message line 1
          message line 2
