---
- name: Check Linux system
  hosts: "{{ lookup('env', 'ANSIBLE_HOST') | default('all', true) }}"
  tasks:
    - name: Check if ansbile role definitions are working correctly
      ansible.builtin.include_role:
        name: check_linux_system